### ISSUE TITLE
2.0.4+ Unexpected token import

### ISSUE THREAD

**Issue by danielhass** [standardnotes/desktop#128]
Hi there,

I'm the maintainer of the AUR standardnotes-desktop package which you can find here:

https://aur.archlinux.org/packages/standardnotes-desktop

Starting with version 2.0.4 I'm facing an strange exception if I try to start the app:

```
App threw an error during load
/opt/standardnotes-desktop/app/index.js:10
import menuManager from './javascripts/menuManager.js'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/usr/bin/standardnotes-desktop:30:19)
    at Object.<anonymous> (/usr/bin/standardnotes-desktop:32:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
A JavaScript error occurred in the main process
Uncaught Exception:
/opt/standardnotes-desktop/app/index.js:10
import menuManager from './javascripts/menuManager.js'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/usr/bin/standardnotes-desktop:30:19)
    at Object.<anonymous> (/usr/bin/standardnotes-desktop:32:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Here you can see how I build the package:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=standardnotes-desktop

I use this JavaScript file to start the app. This allows me to provide the Arch Linux users with an standardnotes-desktop executable:

https://aur.archlinux.org/cgit/aur.git/tree/standardnotes-desktop.js?h=standardnotes-desktop

Any ideas on this?

**Comment by mobitar** [comment]
Hey, we're using ES6 now so the JavaScript needs to be compiled. Check out the build command here: https://github.com/standardnotes/desktop/blob/master/package.json#L43
