### ISSUE TITLE
Unhandled exception when not connected to the Internet

### ISSUE THREAD

**Issue by probonopd** [standardnotes/desktop#168]
App throws an unhandled exception when not connected to the Internet:

```
Error: Error: net::ERR_INTERNET_DISCONNECTED
    at CancellationToken.createPromise (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:79:30)
    at ElectronHttpExecutor.request (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:71:17)
    at GitHubProvider.httpRequest (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/src/Provider.ts:26:26)
    at /run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/src/GitHubProvider.ts:34:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/out/GitHubProvider.js:108:11)
    at /run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:251:37
From previous event:
    at AppImageUpdater.doCheckForUpdates (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at checkForUpdates (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/dist/index.js:149:17)
    at createWindow (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/dist/index.js:144:3)
    at App.<anonymous> (/run/firejail/appimage/.appimage-6499/app/resources/app.asar/dist/index.js:172:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

This is nasty when you are e.g., in a train where there is no Internet. At least a GUI dialog should come up and say you can't work offline (if that is the case).

Reference:
https://github.com/AppImage/appimage.github.io/pull/247

**Comment by mobitar** [comment]
Offline work is definitely a key feature. I just tested version 2.1.25 on Ubuntu 16.04, and do indeed get the same exception, but usage of the application is not affected. What's the visual result you're seeing?

**Comment by probonopd** [comment]
Since I am running this in an automated test, I do not see any GUI output if there is an unhandled exception.

**Comment by mobitar** [comment]
Are you running it automated as part of the AppImage site? Sorry, not sure if I've made the connection with the other issue you linked to..

**Comment by probonopd** [comment]
> Are you running it automated as part of the AppImage site? 

Yes.

> Sorry, not sure if I've made the connection with the other issue you linked to..

https://github.com/AppImage/appimage.github.io/pull/247 is the PR in which the automated test gets run. Once the application passes that test, it gets added to the [AppImageHub](appimage.github.io/apps/) central directory of available AppImages automatically.

But since the test is run without network connectivity and since it currently results in an unhandled exception, the test does not pass.
