### ISSUE TITLE
New Build Error After Update

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#211]
I just tried doing what you said. This is the error log: (Ubuntu 18.04 64 bit)
```
Error: /home/user/.nvm/versions/node/v7.10.1/bin/node exited with code 1
Error output:
sh: 1: prebuild-install: not found
In file included from /usr/include/c++/7/stdlib.h:36:0,
                 from ../vendor/hunspell/src/hunspell/affentry.cxx:4:
/usr/include/c++/7/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affentry.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.15.0-30-generic
gyp ERR! command "/home/user/.nvm/versions/node/v7.10.1/bin/node" "/home/user/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Downloads/desktop/app/node_modules/spellchecker
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 

npm ERR! Linux 4.15.0-30-generic
npm ERR! argv "/home/user/.nvm/versions/node/v7.10.1/bin/node" "/home/user/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/npm-cli.js" "rebuild" "spellchecker@3.4.4"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spellchecker@3.4.4 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spellchecker@3.4.4 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/.npm/_logs/2018-08-12T18_37_22_646Z-debug.log

    at ChildProcess.childProcess.once.code (/home/user/Downloads/desktop/node_modules/builder-util/src/util.ts:251:14)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
From previous event:
    at rebuild (/home/user/Downloads/desktop/node_modules/electron-builder-lib/out/util/yarn.js:234:18)
    at /home/user/Downloads/desktop/node_modules/electron-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild (/home/user/Downloads/desktop/node_modules/electron-builder-lib/out/util/yarn.js:68:17)
    at /home/user/Downloads/desktop/node_modules/electron-builder-lib/src/packager.ts:451:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/home/user/Downloads/desktop/node_modules/electron-builder-lib/out/packager.js:705:7)
    at /home/user/Downloads/desktop/node_modules/electron-builder-lib/src/packager.ts:365:20
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.doBuild (/home/user/Downloads/desktop/node_modules/electron-builder-lib/out/packager.js:615:7)
    at /home/user/Downloads/desktop/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /home/user/Downloads/desktop/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/user/Downloads/desktop/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at Packager._build (/home/user/Downloads/desktop/node_modules/electron-builder-lib/out/packager.js:542:7)
    at /home/user/Downloads/desktop/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/user/Downloads/desktop/node_modules/electron-builder-lib/out/packager.js:501:7)
    at /home/user/Downloads/desktop/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/user/Downloads/desktop/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/home/user/Downloads/desktop/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/home/user/Downloads/desktop/node_modules/electron-builder/src/cli/cli.ts:43:10)

npm ERR! Linux 4.15.0-30-generic
npm ERR! argv "/home/user/.nvm/versions/node/v7.10.1/bin/node" "/home/user/.nvm/versions/node/v7.10.1/bin/npm" "run" "dist-linux"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! standard-notes@2.3.3 dist-linux: `npm run build && electron-builder -l --x64 --ia32`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the standard-notes@2.3.3 dist-linux script 'npm run build && electron-builder -l --x64 --ia32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the standard-notes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && electron-builder -l --x64 --ia32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs standard-notes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls standard-notes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/.npm/_logs/2018-08-12T18_37_23_039Z-debug.log

```

**Comment by infosisio** [comment]
@mobitar I tried this with electron-packager and it extracts the resources but now the Linux executable doesn't even execute.

**Comment by mobitar** [comment]
Sorry, please try this:

```
git pull
npm run setup
npm run start
```

**Comment by infosisio** [comment]
@mobitar Those steps make the application open temporarily but what I need is AppImage/Linux executable. I tried the dist-linux and I get the same error I pasted above.

**Comment by mobitar** [comment]
Try this:

```
sudo apt-get install gcc-multilib g++-multilib
```

then build again.

**Comment by infosisio** [comment]
@mobitar That did the trick it seems ! It would be good to add this in some documentation, Ubuntu is very popular and it's a pity for others to be confused.

**Comment by mobitar** [comment]
It's a sort of environment issue. In any case, this issue will now serve as the documentation :)
