### ISSUE TITLE
Cannot Build Latest Desktop Version

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#230]
Platform: Linux Mint 19 (Base: Ubuntu 18.04)

On native Ubuntu 18.04, only npm run start does not work. 

```
Error: /usr/bin/node exited with code 1
Error output:
prebuild-install WARN install No prebuilt binaries found (target=1.8.4 runtime=electron arch=ia32 platform=linux)
In file included from /usr/include/c++/6/stdlib.h:36:0,
                 from ../vendor/hunspell/src/hunspell/affentry.cxx:4:
/usr/include/c++/6/cstdlib:41:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
make: *** [Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affentry.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/desktop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-33-generic
gyp ERR! command "/usr/bin/node" "/home/user/desktop/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/user/desktop/app/node_modules/spellchecker
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

npm ERR! Linux 4.15.0-33-generic
npm ERR! argv "/usr/bin/node" "/usr/share/npm/bin/npm-cli.js" "rebuild" "spellchecker@3.4.4"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! spellchecker@3.4.4 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spellchecker@3.4.4 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/desktop/app/npm-debug.log

    at ChildProcess.childProcess.once.code (/home/user/desktop/node_modules/builder-util/src/util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
From previous event:
    at rebuild (/home/user/desktop/node_modules/electron-builder-lib/out/util/yarn.js:234:18)
    at /home/user/desktop/node_modules/electron-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at installOrRebuild (/home/user/desktop/node_modules/electron-builder-lib/out/util/yarn.js:68:17)
    at /home/user/desktop/node_modules/electron-builder-lib/src/packager.ts:451:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/home/user/desktop/node_modules/electron-builder-lib/out/packager.js:705:7)
    at /home/user/desktop/node_modules/electron-builder-lib/src/packager.ts:365:20
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.doBuild (/home/user/desktop/node_modules/electron-builder-lib/out/packager.js:615:7)
    at /home/user/desktop/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /home/user/desktop/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/user/desktop/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/user/desktop/node_modules/electron-builder-lib/out/packager.js:542:7)
    at /home/user/desktop/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (/home/user/desktop/node_modules/electron-builder-lib/out/packager.js:501:7)
    at /home/user/desktop/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/user/desktop/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/home/user/desktop/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/home/user/desktop/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at <anonymous>

npm ERR! Linux 4.15.0-33-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dist-linux"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! standard-notes@2.3.4 dist-linux: `npm run build && electron-builder -l --x64 --ia32`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the standard-notes@2.3.4 dist-linux script 'npm run build && electron-builder -l --x64 --ia32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the standard-notes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && electron-builder -l --x64 --ia32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs standard-notes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls standard-notes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/desktop/npm-debug.log
```

**Comment by mobitar** [comment]
I think this is the same issue from before, you need these libraries: https://stackoverflow.com/questions/4643197/missing-include-bits-cconfig-h-when-cross-compiling-64-bit-program-on-32-bit
