### ISSUE TITLE
Help/extensions windows go blank

### ISSUE THREAD

**Issue by jackysee** [standardnotes/desktop#28]
I'm using windows version of standard notes.
When I click **list of extensions** or **help**, the new window just go blank.
The developer console shows it can load the remote site, but some js error.
```
Uncaught Error: Cannot find module 'lodash'Module._resolveFilename @ module.js:455
  Module._resolveFilename @ C:\Users\xxxxxxx\AppData\Local\Programs\standard-notes\resources\electron.asar\common\reset-search-p…:35
  Module._load @ module.js:403
  Module.require @ module.js:483
  require @ internal/module.js:20
  (anonymous function) @ compiled.min-05439d5….js:12
  (anonymous function) @ compiled.min-05439d5….js:12

Uncaught Error: [$injector:modulerr] Failed to instantiate module app.main due to:
Error: [$injector:nomod] Module 'app.main' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.1/$injector/nomod?p0=app.main
    at https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:377
    at https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:11180
    at n (https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:10642)
    at https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:10954
    at https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:20734
    at r (https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:809)
    at d (https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:20582)
    at lt (https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:22564)
    at a (https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:8559)
    at ae (https://standardnotes.org/assets/compiled.min-05439d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js:1:8869)
http://errors.angularjs.org/1.6.1/$injector/modulerr?p0=app.main&p1=Error%3…9d58044b9301ec6498b45feaafb2cec12c10583c6455d45f6a04a522fd74.js%3A1%3A8869)
```
(user name removed in the log)

**Comment by mobitar** [comment]
Hmm, interesting, good catch. I'll take a look at this.

**Comment by mobitar** [comment]
Fixed in latest release: https://github.com/standardnotes/desktop/releases/
