### ISSUE TITLE
Crash on launch: `app.makeSingleInstance is not a function`

### ISSUE THREAD

**Issue by jgierer12** [standardnotes/desktop#358]
After upgrading from `v3.0.9` to `v3.0.12`, the app crashes immediately when trying to launch it:

```
$ standardnotes-desktop 
App threw an error during load
TypeError: app.makeSingleInstance is not a function
    at Object.<anonymous> (/opt/standardnotes-desktop/app/dist/index.js:182:28)
    at Object.<anonymous> (/opt/standardnotes-desktop/app/dist/index.js:212:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/usr/bin/standardnotes-desktop:30:19)
    at Object.<anonymous> (/usr/bin/standardnotes-desktop:32:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
TypeError: app.makeSingleInstance is not a function
    at Object.<anonymous> (/opt/standardnotes-desktop/app/dist/index.js:182:28)
    at Object.<anonymous> (/opt/standardnotes-desktop/app/dist/index.js:212:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/usr/bin/standardnotes-desktop:30:19)
    at Object.<anonymous> (/usr/bin/standardnotes-desktop:32:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
Checking for updates...
Finished checking for updates. Latest version: 3.0.12 Current version: 3.0.12
```

<details>
<summary>System specs</summary>

```
Host: XPS 13 9370 
OS: Manjaro Linux x86_64 
Kernel: Linux 5.1.4-1-MANJARO 
CPU: Intel i7-8550U (8) @ 4.0GHz 
GPU: Intel UHD Graphics 620 
Memory: 4514MiB / 15756MiB 
Resolution: 1920x1080 
Packages: 1408 (pacman) 
Shell: fish 3.0.2 
Terminal: tilix 
DE: GNOME 3.32.2 
Theme: Adwaita 
Icons: Suru++ 
Font: Inter 13 
```

</details>

**Comment by mobitar** [comment]
Strange. Any ideas @rjocoleman?

**Comment by rjocoleman** [comment]
Interesting. @jgierer12 Where did you get the package from - https://standardnotes.org or somewhere else? Is it the Official AppImage or from a distro's package management?

**Comment by MrMette** [comment]
I have the same problem. Mine is from the Arch Linux AUR, so my guess is it's the same for him as he is using Manjaro.

It also gives:
Gtk-WARNING **: 22:17:51.451: Locale not supported by C library.
	Using the fallback 'C' locale

Not sure if that has anything to do with it.

**Comment by rjocoleman** [comment]
Ah, right, AUR is building with Electron 4 (soon to be 5) where as this app is still using the v1 API.
https://electronjs.org/docs/tutorial/electron-versioning

Technically a packaging issue, but I'll see what I can do

**Comment by rjocoleman** [comment]
By the way, this issues does not affect the official `AppImage` available here: https://standardnotes.org/extensions?downloaded=linux

**Comment by rjocoleman** [comment]
@mobitar a fix for this is in #359

**Comment by rjocoleman** [comment]
I've filed a quick note with the AUR package that appears to be used here too with an interim patch, to hopefully alleviate any release pressure - as there is no guarantee @mobitar will agree with the technique used in #359 or be able to release it quickly.

https://aur.archlinux.org/packages/standardnotes-desktop/#news

If anyone effected want's to build and install it themselves and use that package the steps are:
```
git clone https://aur.archlinux.org/standardnotes-desktop.git
cd standardnotes-desktop
curl -O https://gist.githubusercontent.com/rjocoleman/6279ea9f11885f13383867a9b70408a9/raw/d5b8dbef8015ed2c40c858308c01d45f451dfed6/standardnotes-desktop-aur-deprecation.patch
git apply standardnotes-desktop-aur-deprecation.patch
makepkg -si
```

That said - my work doesn't address any other potential API inconsistencies. It only touches the boot check for an existing instance of the app. The official StandardNotes distributed AppImage is the best way to use this application on Linux as it's got all the dependencies at the correct versions (and AUR doesn't allow an elegant way to do that for Electron).

**Comment by MrMette** [comment]
Your patch seemed to be applied into the AUR package and it works again. I also tested the AppImage and that one obviously works as well. I will test next update which one of those is the easiest to update and use that one going forward.

Thank you very much for fixing this so quickly.
Hopefully it's fixed for the original poster as well.

**Comment by jgierer12** [comment]
Yes, the patch fixes the issue for me as well. Thanks a lot @rjocoleman :pray:

**Comment by mobitar** [comment]
Thanks for the quick resolution @rjocoleman! This will be great too as we're wanting to upgrade to Electron 5 in an upcoming release.
