### ISSUE TITLE
sha512 mismatch when updating

### ISSUE THREAD

**Issue by xioren** [standardnotes/desktop#549]
GENERAL

App Version: 3.3.5
Platform: Linux 5.6.0-1
OS Version: Debian Testing
Editor: 

ISSUE

Fails to update and outputs sha512 errors in terminal.

EXPECTED BEHAVIOR

Update successfully.

STEPS TO RECREATE

Run appimage via terminal.

```
[10:51:57:0149] [debug] download range: bytes=26775346-27011682
[10:51:57:0285] [debug] download range: bytes=27044451-27088820
[10:51:57:0469] [debug] download range: bytes=27120783-27654288
[10:51:57:0616] [debug] download range: bytes=27667972-78023455
[10:52:03:0562] [debug] download range: bytes=78131963-78327783
[10:52:03:0695] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected vvveWi3wrQ0viPEMwO7UZYtNxRjTHczL+uZD2ZktFGxppsuBmC7GY1f6sCPNVzLk0OXH1CiWOtkWYZtIyDjZIA==, got hRXqezFlgTzBAgU8UR6lKYiPkghz6PW2D8fY+hZyZH58SwdImI1OWe6zW42uLLXeZPDnXXI1pYBLZALxvFmxJQ==
    at t.newError (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:1:4976)
    at b.validate (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:127:74532)
    at WriteStream.<anonymous> (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:127:114023)
    at WriteStream.emit (events.js:194:13)
    at internal/fs/streams.js:209:14
    at /tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:1:7909
    at FSReqCallback.oncomplete (fs.js:150:20)
[10:52:21:0272] [error] Error: Error: sha512 checksum mismatch, expected vvveWi3wrQ0viPEMwO7UZYtNxRjTHczL+uZD2ZktFGxppsuBmC7GY1f6sCPNVzLk0OXH1CiWOtkWYZtIyDjZIA==, got mK3yQDAnQpB56YQOuXa1vTwfW3BISwGseGt2xwexwfkNd3QNpl+xIqk4gM55pzqKfz01f1pMpGYaoZ0MW+Pzgg==
    at t.newError (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:1:4976)
    at b.validate (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:127:74532)
    at b._flush (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:127:74333)
    at b.prefinish (_stream_transform.js:138:10)
    at b.emit (events.js:194:13)
    at prefinish (_stream_writable.js:635:14)
    at finishMaybe (_stream_writable.js:643:5)
    at endWritable (_stream_writable.js:663:3)
    at b.Writable.end (_stream_writable.js:594:5)
    at IncomingMessage.onend (_stream_readable.js:668:10)
(node:11746) UnhandledPromiseRejectionWarning: Error: sha512 checksum mismatch, expected vvveWi3wrQ0viPEMwO7UZYtNxRjTHczL+uZD2ZktFGxppsuBmC7GY1f6sCPNVzLk0OXH1CiWOtkWYZtIyDjZIA==, got mK3yQDAnQpB56YQOuXa1vTwfW3BISwGseGt2xwexwfkNd3QNpl+xIqk4gM55pzqKfz01f1pMpGYaoZ0MW+Pzgg==
    at t.newError (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:1:4976)
    at b.validate (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:127:74532)
    at b._flush (/tmp/.mount_Standai7Gq2l/resources/app.asar/dist/index.js:127:74333)
    at b.prefinish (_stream_transform.js:138:10)
    at b.emit (events.js:194:13)
    at prefinish (_stream_writable.js:635:14)
    at finishMaybe (_stream_writable.js:643:5)
    at endWritable (_stream_writable.js:663:3)
    at b.Writable.end (_stream_writable.js:594:5)
    at IncomingMessage.onend (_stream_readable.js:668:10)
(node:11746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Data backup succesfully saved:  2020-05-08T17-53-33.550Z.txt
```

**Comment by JaspalSuri** [comment]
Hi, I'm sorry that the AppImage isn't updating properly. Can you try the [Snap](https://snapcraft.io/standard-notes) to see if that works better?

**Comment by xioren** [comment]
No thank you, I think i'd rather stick with a broken appimage than install snap.

**Comment by JaspalSuri** [comment]
I've assigned our desktop dev to look into this. Thanks for your patience!

**Comment by mobitar** [comment]
Sorry about that, should be fixed now.

**Comment by xioren** [comment]
I can confirm it's working on my end. Thanks guys!
