### ISSUE TITLE
TypeError during beta upgrade

### ISSUE THREAD

**Issue by pcrockett** [standardnotes/desktop#624]
Just reporting a minor issue to help with the beta. This doesn't actually seem to have any negative effect - everything seems to be working fine, at least on the surface.

I upgraded from 3.4.10 to 3.5.1-beta05. On the first run, I ran Standard Notes from a terminal and saw the following TypeError in the output:

```plaintext
PackageManager: TypeError: Cannot read property 'name' of undefined
    at /tmp/.mount_standaNVp2OZ/resources/app.asar/dist/index.js:22:259340
    at Array.map (<anonymous>)
    at Me (/tmp/.mount_standaNVp2OZ/resources/app.asar/dist/index.js:22:259277)
    at Ue (/tmp/.mount_standaNVp2OZ/resources/app.asar/dist/index.js:22:259177)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async /tmp/.mount_standaNVp2OZ/resources/app.asar/dist/index.js:22:258798
    at async IpcMainImpl.<anonymous> (/tmp/.mount_standaNVp2OZ/resources/app.asar/dist/index.js:22:258741)
```

[Here's the full log.](https://github.com/standardnotes/desktop/files/5443437/log.txt)

So far the beta looks great. Thanks!

**Comment by JaspalSuri** [comment]
Thanks for the report! Which Linux distro were you using at the time?

**Comment by pcrockett** [comment]
EndeavourOS with i3wm.

**Comment by JaspalSuri** [comment]
Thanks for that info!

**Comment by baptiste-grob** [comment]
Thanks for the report, should be fixed in the next beta. Do you have any third-party extensions installed?

**Comment by pcrockett** [comment]
Yes, I have plenty of them installed. You should see a list of them in the log I attached above (checking for updates etc).

**Comment by baptiste-grob** [comment]
I only saw extensions that come from us, so that's why I asked just to be sure. 🙂

**Comment by pcrockett** [comment]
Ohh, I missed the _third-party_ part... No, no third-party extensions.
