### ISSUE TITLE
Building on Linux fails

### ISSUE THREAD

**Issue by julian-fairfax** [standardnotes/desktop#677]
Hi,
I'm trying to build this app on Linux. I've followed the instructions and run `yarn setup` followed by `yarn build` (after having install libsecret-1-dev and python2 using `sudo apt install libsecret-1-dev python2` and yarn with `npm install --global yarn`) and I end up with multiple errors. Thanks for your help and thanks for developing this wondeful app! Here's the log:
```
yarn run v1.22.10
$ yarn && yarn --cwd ./app && git submodule update --init && yarn --cwd ./web
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning package.json: No license field
warning standard-notes@3.6.1: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Submodule 'app/extensions/batch-manager' (https://github.com/sn-extensions/batch-manager.git) registered for path 'app/extensions/batch-manager'
Submodule 'app/extensions/extensions-manager' (https://github.com/sn-extensions/extensions-manager.git) registered for path 'app/extensions/extensions-manager'
Submodule 'web' (https://github.com/standardnotes/web.git) registered for path 'web'
Cloning into '/home/julian/Code/standardnotes/desktop/app/extensions/batch-manager'...
Cloning into '/home/julian/Code/standardnotes/desktop/app/extensions/extensions-manager'...
Cloning into '/home/julian/Code/standardnotes/desktop/web'...
Submodule path 'app/extensions/batch-manager': checked out '2d1ba6ac9f09193e40c4241a70605ecb3c15d3c7'
Submodule path 'app/extensions/extensions-manager': checked out 'c8a614bf093a3d6ab95ea8eb5e7507b152ed49e2'
Submodule path 'web': checked out 'f007459c350107f00ba771bc923da77bf6d31b6e'
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @reach/alert@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning " > @reach/alert@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert > @reach/utils@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning "@reach/alert > @reach/utils@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert > @reach/visually-hidden@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning "@reach/alert > @reach/visually-hidden@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning " > @reach/alert-dialog@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning " > @reach/alert-dialog@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/auto-id@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/auto-id@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning " > @reach/dialog@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning " > @reach/dialog@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/dialog > @reach/portal@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/dialog > @reach/portal@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/dialog > react-focus-lock@2.5.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@reach/alert-dialog > @reach/dialog > react-remove-scroll@2.4.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@reach/alert-dialog > @reach/dialog > react-focus-lock > react-clientside-effect@1.2.2" has unmet peer dependency "react@^15.3.0 || ^16.0.0".
warning "@reach/alert-dialog > @reach/dialog > react-focus-lock > use-callback-ref@1.2.4" has unmet peer dependency "react@^16.8.0".
warning "@reach/alert-dialog > @reach/dialog > react-focus-lock > use-sidecar@1.0.3" has unmet peer dependency "react@^16.8.0".
warning "@reach/alert-dialog > @reach/dialog > react-remove-scroll > react-remove-scroll-bar@2.1.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@reach/alert-dialog > @reach/dialog > react-remove-scroll > react-style-singleton@2.1.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
[4/4] Building fresh packages...
Done in 121.06s.
```
---
```
yarn run v1.22.10
$ yarn lint && yarn build:web && node scripts/build.mjs
$ npm-run-all --parallel lint:*
$ eslint app/index.ts app/application.ts app/javascripts/**/*.ts
$ prettier --check .
$ tsc --noEmit
Checking formatting...
All matched files use Prettier code style!
$ git submodule update && cd web && rimraf node_modules && yarn setup && yarn run bundle:desktop
$ yarn submodules && yarn install
$ git submodule update --init --force
Submodule 'app/extensions/extensions-manager' (https://github.com/sn-extensions/extensions-manager.git) registered for path 'app/extensions/extensions-manager'
Submodule 'public/extensions/batch-manager' (https://github.com/sn-extensions/batch-manager.git) registered for path 'public/extensions/batch-manager'
Submodule 'public/extensions/extensions-manager' (https://github.com/sn-extensions/extensions-manager.git) registered for path 'public/extensions/extensions-manager'
Submodule 'vendor/extensions/extensions-manager' (https://github.com/sn-extensions/extensions-manager.git) registered for path 'vendor/extensions/extensions-manager'
Cloning into '/home/julian/Code/standardnotes/desktop/web/app/extensions/extensions-manager'...
Cloning into '/home/julian/Code/standardnotes/desktop/web/public/extensions/batch-manager'...
Cloning into '/home/julian/Code/standardnotes/desktop/web/public/extensions/extensions-manager'...
Cloning into '/home/julian/Code/standardnotes/desktop/web/vendor/extensions/extensions-manager'...
Submodule path 'app/extensions/extensions-manager': checked out '206c1da0a4bcd2389a052863de03251b103b7335'
Submodule path 'public/extensions/batch-manager': checked out '2d1ba6ac9f09193e40c4241a70605ecb3c15d3c7'
Submodule path 'public/extensions/extensions-manager': checked out '206c1da0a4bcd2389a052863de03251b103b7335'
Submodule path 'vendor/extensions/extensions-manager': checked out '206c1da0a4bcd2389a052863de03251b103b7335'
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @reach/alert@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning " > @reach/alert@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert > @reach/utils@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning "@reach/alert > @reach/utils@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert > @reach/visually-hidden@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning "@reach/alert > @reach/visually-hidden@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning " > @reach/alert-dialog@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning " > @reach/alert-dialog@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/auto-id@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/auto-id@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning " > @reach/dialog@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning " > @reach/dialog@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/dialog > @reach/portal@0.13.0" has unmet peer dependency "react@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/dialog > @reach/portal@0.13.0" has unmet peer dependency "react-dom@^16.8.0 || 17.x".
warning "@reach/alert-dialog > @reach/dialog > react-focus-lock@2.5.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@reach/alert-dialog > @reach/dialog > react-remove-scroll@2.4.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@reach/alert-dialog > @reach/dialog > react-focus-lock > react-clientside-effect@1.2.2" has unmet peer dependency "react@^15.3.0 || ^16.0.0".
warning "@reach/alert-dialog > @reach/dialog > react-focus-lock > use-callback-ref@1.2.4" has unmet peer dependency "react@^16.8.0".
warning "@reach/alert-dialog > @reach/dialog > react-focus-lock > use-sidecar@1.0.3" has unmet peer dependency "react@^16.8.0".
warning "@reach/alert-dialog > @reach/dialog > react-remove-scroll > react-remove-scroll-bar@2.1.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@reach/alert-dialog > @reach/dialog > react-remove-scroll > react-style-singleton@2.1.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
[4/4] Building fresh packages...
$ webpack --config webpack.prod.js --env.platform='desktop'
Hash: fda30922ff81b1f6b6dc
Version: webpack 4.44.2
Time: 30491ms
Built at: 03/13/2021 9:32:01 PM
 2 assets
Entrypoint main = ./javascripts/app.js ./javascripts/app.js.map
 [10] ./app/assets/javascripts/utils.ts 4.58 KiB {0} [built]
[158] ./app/assets/javascripts/views/index.ts 2.09 KiB {0} [built]
[173] ./app/assets/javascripts/services/errorReporting.ts 4.02 KiB {0} [built]
[176] ./app/assets/javascripts/index.ts 646 bytes {0} [built]
[182] ./app/assets/stylesheets/index.css.scss 3.17 KiB {0} [built] [failed] [1 error]
[184] ./vendor/assets/javascripts/angular-sanitize.js 25.8 KiB {0} [built]
[185] ./vendor/assets/javascripts/zip/deflate.js 72.4 KiB {0} [built]
[186] ./vendor/assets/javascripts/zip/inflate.js 66.2 KiB {0} [built]
[187] ./vendor/assets/javascripts/zip/zip.js 32.3 KiB {0} [built]
[188] ./vendor/assets/javascripts/zip/z-worker.js 3.99 KiB {0} [built]
[189] ./app/assets/javascripts/app.ts 4.75 KiB {0} [built]
[190] ./app/assets/javascripts/routes.ts 546 bytes {0} [built]
[191] ./app/assets/javascripts/ui_models/application_group.ts 2.42 KiB {0} [built]
[329] ./app/assets/javascripts/views/account_switcher/account_switcher.ts 2.63 KiB {0} [built]
[434] ./app/assets/javascripts/directives/functional/index.ts 1.85 KiB {0} [built]
    + 494 hidden modules

ERROR in ./node_modules/@reach/dialog/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Module did not self-register: '/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/vendor/linux-x64-88/binding.node'.
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at getDefaultSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/index.js:40:61)
    at /home/julian/Code/standardnotes/desktop/web/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/julian/Code/standardnotes/desktop/web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/julian/Code/standardnotes/desktop/web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/julian/Code/standardnotes/desktop/web/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)
 @ ./app/assets/javascripts/index.ts 7:0-35

ERROR in ./node_modules/sn-stylekit/dist/stylekit.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Module did not self-register: '/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/vendor/linux-x64-88/binding.node'.
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at getDefaultSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/index.js:40:61)
    at /home/julian/Code/standardnotes/desktop/web/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/julian/Code/standardnotes/desktop/web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/julian/Code/standardnotes/desktop/web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/julian/Code/standardnotes/desktop/web/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)
 @ ./app/assets/javascripts/index.ts 9:0-40

ERROR in ./app/assets/stylesheets/index.css.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: The module '/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/vendor/linux-x64-88/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 88. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at getDefaultSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/index.js:40:61)
    at /home/julian/Code/standardnotes/desktop/web/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/julian/Code/standardnotes/desktop/web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/julian/Code/standardnotes/desktop/web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/julian/Code/standardnotes/desktop/web/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)
 @ ./app/assets/javascripts/index.ts 11:0-40
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!app/assets/stylesheets/index.css.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./app/assets/stylesheets/index.css.scss 1.96 KiB {0} [built] [failed] [1 error]
    
    ERROR in ./app/assets/stylesheets/index.css.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./app/assets/stylesheets/index.css.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: The module '/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/vendor/linux-x64-88/binding.node'
    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 70. This version of Node.js requires
    NODE_MODULE_VERSION 88. Please try re-compiling or re-installing
    the module (for instance, using `npm rebuild` or `npm install`).
        at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
        at Module.load (node:internal/modules/cjs/loader:972:32)
        at Function.Module._load (node:internal/modules/cjs/loader:813:14)
        at Module.require (node:internal/modules/cjs/loader:996:19)
        at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at module.exports (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/binding.js:19:10)
        at Object.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/index.js:14:35)
        at Module._compile (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
        at Module.load (node:internal/modules/cjs/loader:972:32)
        at Function.Module._load (node:internal/modules/cjs/loader:813:14)
        at Module.require (node:internal/modules/cjs/loader:996:19)
        at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at getDefaultSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
        at getSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
        at Object.loader (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/index.js:40:61)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!node_modules/@reach/dialog/styles.css:
    Entrypoint mini-css-extract-plugin = *
       1 module
    
    ERROR in ./node_modules/@reach/dialog/styles.css (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/@reach/dialog/styles.css)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: Module did not self-register: '/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/vendor/linux-x64-88/binding.node'.
        at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
        at Module.load (node:internal/modules/cjs/loader:972:32)
        at Function.Module._load (node:internal/modules/cjs/loader:813:14)
        at Module.require (node:internal/modules/cjs/loader:996:19)
        at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at module.exports (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/binding.js:19:10)
        at Object.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/index.js:14:35)
        at Module._compile (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
        at Module.load (node:internal/modules/cjs/loader:972:32)
        at Function.Module._load (node:internal/modules/cjs/loader:813:14)
        at Module.require (node:internal/modules/cjs/loader:996:19)
        at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at getDefaultSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
        at getSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
        at Object.loader (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/index.js:40:61)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!node_modules/sn-stylekit/dist/stylekit.css:
    Entrypoint mini-css-extract-plugin = *
       1 module
    
    ERROR in ./node_modules/sn-stylekit/dist/stylekit.css (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/sn-stylekit/dist/stylekit.css)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: Module did not self-register: '/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/vendor/linux-x64-88/binding.node'.
        at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
        at Module.load (node:internal/modules/cjs/loader:972:32)
        at Function.Module._load (node:internal/modules/cjs/loader:813:14)
        at Module.require (node:internal/modules/cjs/loader:996:19)
        at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at module.exports (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/binding.js:19:10)
        at Object.<anonymous> (/home/julian/Code/standardnotes/desktop/web/node_modules/node-sass/lib/index.js:14:35)
        at Module._compile (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
        at Module.load (node:internal/modules/cjs/loader:972:32)
        at Function.Module._load (node:internal/modules/cjs/loader:813:14)
        at Module.require (node:internal/modules/cjs/loader:996:19)
        at require (/home/julian/Code/standardnotes/desktop/web/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at getDefaultSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
        at getSassImplementation (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
        at Object.loader (/home/julian/Code/standardnotes/desktop/web/node_modules/sass-loader/dist/index.js:40:61)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by julian-fairfax** [comment]
Fixed this by upgrading node:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```
